import csv
import sys
import os

def generate_files(csv_filename):
    if not os.path.exists(csv_filename):
        print(f"Error: {csv_filename} not found.")
        sys.exit(1)

    registers = []
    with open(csv_filename, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            # 빈 줄 무시
            if row['Name'].strip():
                registers.append(row)

    # 1. regmap.h 자동 생성 (기존 regmap.h 대체)
    with open('regmap.h', 'w', encoding='utf-8') as f:
        f.write("// ==========================================\n")
        f.write("// AUTO-GENERATED FILE by gen_regs.py\n")
        f.write("// DO NOT EDIT THIS FILE DIRECTLY.\n")
        f.write("// ==========================================\n")
        f.write("#ifndef _REGMAP_H_\n#define _REGMAP_H_\n\n")
        
        for reg in registers:
            name = reg['Name'].strip()
            page = reg['Page'].strip()
            addr = reg['Address'].strip()
            desc = reg.get('Description', '').strip()
            f.write(f"#define {name:<30} regmap[{page}][{addr}]  // {desc}\n")
            
        f.write("\n#endif // _REGMAP_H_\n")

    # 2. reg_table.h 자동 생성 (util_reg.c에서 사용될 파싱 테이블)
    with open('reg_table.h', 'w', encoding='utf-8') as f:
        f.write("// ==========================================\n")
        f.write("// AUTO-GENERATED FILE by gen_regs.py\n")
        f.write("// DO NOT EDIT THIS FILE DIRECTLY.\n")
        f.write("// ==========================================\n")
        f.write("#ifndef _REG_TABLE_H_\n#define _REG_TABLE_H_\n\n")
        f.write('#include "regmap.h"\n\n')
        f.write("typedef struct {\n    const char *name;\n    int *ptr;\n} ConfigMap;\n\n")
        
        f.write("static ConfigMap config_table[] = {\n")
        for reg in registers:
            name = reg['Name'].strip()
            f.write(f'    {{"{name}", &{name}}},\n')
        f.write("};\n\n")
        f.write("static const int config_table_size = sizeof(config_table) / sizeof(config_table[0]);\n\n")
        f.write("#endif // _REG_TABLE_H_\n")

    print("Successfully generated 'regmap.h' and 'reg_table.h'.")

if __name__ == "__main__":
    generate_files('registers.csv')